version: '3.8'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/mydb
      - PORT=4000
    depends_on:
      - db
    ports:
      - "4000:4000"

  frontend:
    build: .
    environment:
      - NEXT_PUBLIC_API_URL=http://168.231.112.206:4000
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  pgdata: